[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "west typical stock economy know absent message expand breeze doctor diamond guess spoil join interest merge loan country raven scheme gospel office attack until"
  